web/router.ex
defmodule Ipseeds.Router do
  use Ipseeds.Web, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug Ipseeds.LocalePlug, "en"
  end

  pipeline :csrf_protection do
    plug :protect_from_forgery
  end

  pipeline :public_layout do
    plug Ipseeds.CountingPlug
    plug :put_layout, {Ipseeds.LayoutView, :public}
  end

  pipeline :secure_app do
    plug Ipseeds.App.AuthPlug
    plug Ipseeds.App.KeypairCheckPlug
  end

  pipeline :app_layout do
    plug Ipseeds.CountingPlug
    plug Ipseeds.App.UnreadMessagesPlug
    plug Ipseeds.App.PendingContractsPlug
    plug :put_layout, {Ipseeds.LayoutView, :app}
  end

  pipeline :secure_admin do
    plug Ipseeds.Admin.AuthPlug, repo: Ipseeds.Repo
  end

  pipeline :admin_layout do
    plug :put_layout, {Ipseeds.LayoutView, :admin}
  end

  scope "/", Ipseeds do
    # Will redirect to /:locale/
    pipe_through [:browser, :csrf_protection]

    get "/", PageController, :dummy

    # add dummy route to allow links to this page with no locale to redirect to locale
    get "/users/reset_password", PageController, :dummy
  end

  scope "/:locale", Ipseeds do
    # Public routes (static pages, contact page)
    pipe_through [:browser, :csrf_protection, :public_layout]

    get "/", PageController, :index
    get "/privacy_policy", PageController, :privacy_policy
    get "/terms", PageController, :terms
    get "/features", PageController, :features
    get "/faq", PageController, :faq
    get "/about", PageController, :about
    get "/how_it_works", PageController, :how_it_works
    get "/pricing", PageController, :pricing
    get "/medium_rss_feed", PageController, :medium_rss_feed

    # Subscribe
    post "/subscribe", SubscribeController, :subscribe

    # Contact Page routes 
    get "/contact_us", ContactUsController, :new
    post "/contact_us", ContactUsController, :create

    # User Registration routes
    resources "/user_registrations", UserRegistrationController, only: [:new, :create]
    get "/user_registrations/thank_you", UserRegistrationController, :thank_you

    # Public User routes
    get "/users/forgot_password", UserController, :forgot_password
    post "/users/request_reset_password", UserController, :request_reset_password
    get "/users/reset_password", UserController, :reset_password
    post "/users/submit_new_password", UserController, :submit_new_password

    # Session routes
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    # Explorer routes
    resources "/explorer", App.ExplorerController, only: [:index, :show]
  end

  scope "/:locale", Ipseeds do
    pipe_through [:browser]
    post "/_reset_password_hook", UserController, :api_password_reset_hook

    # For monitoring
    get "/health_check", PageController, :health_check
  end

  scope "/:locale/secure", Ipseeds, as: :app do
    # App routes (main ipseeds functionality)
    pipe_through [:browser, :csrf_protection, :secure_app, :app_layout]

    get "/", App.IpDiscoveryController, :index
    get "/features", PageController, :features
    get "/privacy_policy", PageController, :privacy_policy
    get "/terms", PageController, :terms
    get "/faq", PageController, :faq
    get "/about", PageController, :about
    get "/how_it_works", PageController, :how_it_works

    get "/contact_us", ContactUsController, :new
    post "/contact_us", ContactUsController, :create

    # User settings routes
    get "/users/passphrase", App.UserController, :passphrase
    post "/users/passphrase", App.UserController, :create_passphrase
    post "/users/reset_password", App.UserController, :reset_password
    resources "/users", App.UserController, only: [:show, :edit, :update]
    post "/users/:id/update_profile_photo", App.UserController, :update_profile_photo

    # Ip Notary routes
    resources "/ip_notaries", App.IpNotaryController, only: [:new, :create, :index, :show]
    resources "/ip_summaries", App.IpSummaryController, 
      only: [:new, :create, :index, :show, :edit, :update]
    post "/ip_summaries/ip_notaries_list", App.IpSummaryController, :ip_notaries_list
    patch "/ip_summaries/:asset_id/hide", App.IpSummaryController, :hide
    patch "/ip_summaries/:asset_id/unhide", App.IpSummaryController, :unhide

    # Messages and contact list
    resources "/messages", App.MessageController, except: [:show]
    get "/messages/:username/:subject", App.MessageController, :show
    patch "/messages/mark_as_read/:user_id/:subject", App.MessageController, :mark_as_read
    resources "/user_contacts", App.UserContactController, only: [:index, :create, :delete]

    # Contract/Licensing
    resources "/contracts", App.ContractController, only: [:new, :create, :index, :show]

    get "/sessions/update", SessionController, :update
    
    # Explorer routes
    resources "/explorer", App.ExplorerController, only: [:index, :show]

    # Agreeable Contract routes
    resources "/agreeable_contract", App.AgreeableContractController, except: [:index, :delete]
    patch "/agreeable_contract/:id/cancel", App.AgreeableContractController, :cancel
    patch "/agreeable_contract/:id/decline", App.AgreeableContractController, :decline
  end

  scope "/:locale/admin", Ipseeds, as: :public_admin do
    # Public admin routes (no auth needed to view)
    pipe_through [:browser, :csrf_protection, :admin_layout]

    resources "/sessions", Admin.SessionController, only: [:new, :create, :delete]
    resources "/password_reset", Admin.PasswordResetController,
      only: [:new, :create, :edit, :update]
  end

  scope "/:locale/admin", Ipseeds, as: :admin do
    # Admin routes (TRPMA admin functionality)
    pipe_through [:browser, :csrf_protection, :secure_admin, :admin_layout]

    get "/", Admin.PageController, :dashboard

    resources "/admin_users", Admin.AdminUserController, except: [:show]
    resources "/user_registrations", Admin.UserRegistrationController,
      only: [:index, :show, :edit, :update]
    post "/user_registrations/:id/approve", Admin.UserRegistrationController, :approve
    post "/user_registrations/:id/disapprove", Admin.UserRegistrationController, :disapprove
  end
end

web/models/contract.ex
defmodule Ipseeds.Contract do
  use Ipseeds.Web, :model
  use Ipseeds.AttachmentHelpers

  alias Ipseeds.ContractAttachment
  alias Ipseeds.User

  @allowed_fields ~w(issuer_user_id recipient_user_id main_attachment_id api_transaction_id
    api_sent_asset_id)a
  @required_fields ~w(issuer_user_id recipient_user_id api_transaction_id)a

  schema "contracts" do
    belongs_to :issuer, User, foreign_key: :issuer_user_id 
    belongs_to :recipient, User, foreign_key: :recipient_user_id
    field :api_transaction_id, :string
    field :api_sent_asset_id, :string

    has_many :attachments, ContractAttachment
    belongs_to :main_attachment, ContractAttachment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @allowed_fields)
    |> validate_required(@required_fields)
  end

  def visible_to_user_query(user_id, query \\ default_query()) do
    from contract in query,
      left_join: a in assoc(contract, :main_attachment),
      join: i in assoc(contract, :issuer),
      join: r in assoc(contract, :recipient),
      where: contract.issuer_user_id == ^user_id or contract.recipient_user_id == ^user_id,
      preload: [main_attachment: a, issuer: i, recipient: r]
  end 

  defp default_query() do
    from contract in __MODULE__, select: contract
  end
end

web/controllers/app/contract_controller.ex
defmodule Ipseeds.App.ContractController do
  use Ipseeds.Web, :controller
  use Ipseeds.AssetHelpers, asset_module: Ipseeds.Contract,
    asset_api_id_key: :tx_id, asset_db_id_key: :api_transaction_id

  import Ipseeds.ParamPlug
  
  require Logger

  alias Ecto.Multi
  alias Ipseeds.{API, Contract, ContractAttachment, EnumHelpers, User, AgreeableContract, ExagonHelpers,
    AttachmentHelpers}

  plug :strip_tags, "contract" when action in [:create, :update]
  plug :scrub_params, "contract" when action in [:create, :update]

  def index(conn, _params) do
    user = conn.assigns.current_user
    receiver_address = get_session(conn, :receiver_address)
    {conn, contracts_from_api} = 
      with {conn, sent_contracts} <- query_for_sent_contracts(conn),
           {conn, received_contracts} <- query_for_received_contracts(conn, receiver_address),
      do: {conn, Enum.concat(sent_contracts, received_contracts)}

    mix_contracts =
      case Enum.empty?(contracts_from_api) do
        true -> []
        _ ->
          contracts_query = contracts_from_api
            |> Enum.map(fn c -> c["tx_id"] end)
            |> get_contracts_query(user)

          contracts_results = contracts_from_api
            |> Enum.map(&EnumHelpers.atomize_keys/1)
            |> merge_db_fields(contracts_query)

          contracts_from_api
          |> Enum.map(&EnumHelpers.atomize_keys/1)
          |> merge_recipient_user_id_by_receive_address()
          |> Enum.filter(fn(x) -> Map.has_key?(x, :status) end)
          |> Enum.concat(contracts_results)
          |> Enum.sort(fn (a, b) -> a[:tx_time] > b[:tx_time] end)

      end

    render(conn, "index.html", contracts: mix_contracts)
  end

  def new(conn, _params) do
    changeset = Contract.changeset(%Contract{})

    conn
    |> ExagonHelpers.put(attachment_max_size_bytes: Contract.attachment_max_size_bytes(),
        file_too_big_error: gettext("File exceeds maximum allowed size of %{size_limit}",
          size_limit: AttachmentHelpers.human_readable_attachment_max_size(Contract))
      )
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"contract" => contract_params, "ip_notary_asset_id" => asset_id,
    "main_attachment" => attachment}) do

    conn =
      conn
      |> ExagonHelpers.put(attachment_max_size_bytes: Contract.attachment_max_size_bytes(),
          file_too_big_error: gettext("File exceeds maximum allowed size of %{size_limit}",
          size_limit: AttachmentHelpers.human_readable_attachment_max_size(Contract))
        )

    params = contract_params
      |> Map.put("issuer_user_id", conn.assigns.current_user.id)
      |> Map.put("api_sent_asset_id", asset_id)
      |> Map.put("api_transaction_id", "!TEMP_TX_ID!")

    action_batch = insert_contract_to_db(params, attachment)

    case Repo.transaction(action_batch) do
      {:ok, changeset} ->
        {conn, result} = send_asset(conn, asset_id, contract_params["recipient_user_id"])
        case result do
          {:ok, %{body: %{"txid" => tx_id}}} ->
            contract_changes = changeset.contract
              |> Contract.changeset(%{"api_transaction_id" => tx_id})

            case Repo.update(contract_changes) do
              {:ok, contract} ->
                recipient_user = Repo.get(User, contract.recipient_user_id)
                send_new_data_contract_email(recipient_user, contract)

                conn
                |> put_status(:created)
                |> render("create_success.json",
                  redirect_to: app_contract_path(conn, :index, conn.assigns.locale))
              _ ->
                conn
                |> put_status(:unprocessable_entity)
                |> render(Ipseeds.ChangesetView, "error.json", changeset: contract_changes)
            end
          _ ->
            rollback_contract(changeset)
            render(conn, Ipseeds.ErrorView, "403.json", %{message: gettext("API error")})
        end
      {:error, _failed_operations, failed_changeset, _changes_so_far} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(Ipseeds.ChangesetView, "error.json", changeset: failed_changeset)
    end
  end

  def show(conn, %{"id" => api_transaction_id}) do
    current_user = conn.assigns.current_user
    contract_query = get_contract_query(api_transaction_id, current_user)
    contract = Repo.one!(contract_query)
    asset = get_contract_asset(contract)
    current_user_active_keypair = User.active_keypair(current_user)
    recipient_name = User.get_name(contract.recipient)
    issuer_name = User.get_name(contract.issuer)

    conn
    |> Ipseeds.ExagonHelpers.put(%{
        current_user_bip32_public_key: current_user_active_keypair.bip32_hd_public_key,
        main_attachment: Map.take(contract.main_attachment, [:mime_type, :original_filename, :s3_filename]),
        main_attachment_url: Ipseeds.ContractAttachmentUploader.url(
          {contract.main_attachment.s3_filename, contract.main_attachment}, :original),
        main_attachment_hash: asset.hash_attachment
      })
    |> render("show.html", contract: contract, asset: asset, recipient_name: recipient_name,
      issuer_name: issuer_name)
  end

  def edit(conn, %{"id" => id}) do
    contract = Repo.get!(Contract, id)
    changeset = Contract.changeset(contract)
    render(conn, "edit.html", contract: contract, changeset: changeset)
  end

  def update(conn, %{"id" => id, "contract" => contract_params}) do
    contract = Repo.get!(Contract, id)
    changeset = Contract.changeset(contract, contract_params)

    case Repo.update(changeset) do
      {:ok, contract} ->
        conn
        |> put_flash(:info, "Contract updated successfully.")
        |> redirect(to: app_contract_path(conn, :show, conn.assigns.locale, contract))
      {:error, changeset} ->
        render(conn, "edit.html", contract: contract, changeset: changeset)
    end
  end

  def merge_db_fields([], _query), do: []
  def merge_db_fields(contract = %{}, query), do: merge_db_fields([contract], query)
  def merge_db_fields(contracts, contracts_query) when is_list(contracts) do
    contract_map = EnumHelpers.mapify_map_list(contracts, :tx_id)

    contracts_query
    |> Repo.all
    |> Enum.map(fn db_record ->
      contract_map[db_record.api_transaction_id]
      |> Map.merge(%{status: nil})
      |> EnumHelpers.merge_map_fields(db_record, [:recipient_user_id, :recipient, :issuer])
    end)
  end

  defp send_asset(conn, asset_id, recipient_user_id) do
    payload = %{address: get_session(conn, :issuer_address)}
    {conn, balance_resp} = API.call_authed_endpoint(conn, "/tradechain/asset/balance", payload)
    case balance_resp do
      {:ok, %{body: %{"list" => asset_list}}} ->
        has_asset = Enum.any?(asset_list, fn asset ->
          asset["asset_id"] == asset_id
        end)

        {conn, _} = 
          case has_asset do
            false -> call_issue_api(conn, asset_id)
            _ -> {conn, "nothing happened"}
          end

        call_send_api(conn, asset_id, recipient_user_id)
      _ -> {conn, balance_resp}
    end
  end

  defp call_send_api(conn, asset_id, recipient_user_id) do
    recipient_user = Repo.get_by(User.is_active_query, id: recipient_user_id)
    if recipient_user do
      recipient_addr = recipient_user.receiver_asset_addr
      payload = %{
        "address" => get_session(conn, :issuer_address),
        "asset_id" => asset_id,
        "asset_addr_to" => recipient_addr,
        "quantity" => "1"
      }

      API.call_authed_endpoint(conn, "/tradechain/asset/send", payload)
    else
      {conn, {:error, gettext("Error!")}}
    end
  end

  defp call_issue_api(conn, asset_id) do
    payload = %{
      "asset_id" => asset_id,
      "address" => get_session(conn, :issuer_address),
      "quantity" => "10000"
    }
    API.call_authed_endpoint(conn, "/tradechain/asset/issue", payload)
  end

  defp insert_contract_to_db(contract_params, attachment_params) do
    Multi.new
    |> Multi.insert(:contract, Contract.changeset(%Contract{}, contract_params))
    |> Multi.run(:main_attachment, &insert_main_attachment(attachment_params, &1))
    |> Multi.run(:add_main_attachment_id, &add_main_attachment_id(&1))
  end

  defp insert_main_attachment(attachment_params, changes) do
    changes.contract
    |> build_assoc(:attachments)
    |> ContractAttachment.create_changeset(attachment_params)
    |> Repo.insert
  end

  defp add_main_attachment_id(changes) do
    main_attachment_id = changes.main_attachment.id

    changes.contract
    |> Ecto.Changeset.change(main_attachment_id: main_attachment_id)
    |> Repo.update
  end

  defp rollback_contract(%{contract: contract, main_attachment: attachment}) do
    Multi.new
    |> Multi.delete(:main_attachment, attachment)
    |> Multi.delete(:contract, contract)
    |> Repo.transaction
  end

  defp get_contract_asset(contract) do
    case API.call_endpoint("/asset/query", asset_id: contract.api_sent_asset_id) do
      {:ok, %{body: %{} = asset_params}} -> EnumHelpers.atomize_keys(asset_params)
      _ -> nil
    end
  end

  defp get_contract_query(api_transaction_id, current_user) do
    from c in Contract,
      join: i in assoc(c, :issuer),
      join: r in assoc(c, :recipient),
      join: ma in assoc(c, :main_attachment),
      where: c.api_transaction_id == ^api_transaction_id and
        (c.issuer_user_id == ^current_user.id or c.recipient_user_id == ^current_user.id),
      preload: [issuer: i, recipient: r, main_attachment: ma]
  end

  defp send_new_data_contract_email(recipient_user, contract) do
    issuer_user = Repo.get!(User, contract.issuer_user_id)
    Ipseeds.Email.new_data_contract_email(recipient_user, issuer_user)
    |> Ipseeds.Mailer.deliver_later()
  end

  defp query_for_sent_contracts(conn) do
    payload = %{
      "address" => get_session(conn, :issuer_address),
      "tx_time" => 0
    }

    {conn, resp} = API.call_authed_endpoint(conn, "/tradechain/asset/txs", payload)
    case resp do

web/templates/app/contract/_contracts_header.html.eex
<div class="tag1">
  <%= link_unless_current @conn, to: app_contract_path(@conn, :index, @locale), active_class: "on" do %>
    <span><%= gettext "List" %></span>
  <% end %>
  <%= link_unless_current @conn, to: app_contract_path(@conn, :new, @locale), active_class: "on" do %>
    <span><%= gettext "+Issue Data Contract" %></span>
  <% end %>
  <%= link_unless_current @conn, to: app_agreeable_contract_path(@conn, :new, @locale), active_class: "on" do %>
    <span><%= gettext "+Issue NDA" %></span>
  <% end %>
  <%= if details_tab = Map.get(assigns, :detail_tab) do %>
    <%= link_unless_current(
            @conn,
            to: details_tab[:link],
            active_class: "on") do %>
      <span><%= details_tab[:text] %></span>
    <% end %>
  <% end %>
</div>

web/templates/app/contract/index.html.eex
<div class="w1200 cont">
  <%= if Ipseeds.BrowserHelpers.partially_supported_browser?(@conn) do %>
    <%= render Ipseeds.SharedView, "_partially_supported_browser.html", additional_message: gettext "You will be unable to issue or decrypt contracts in your current browser. Please download one of the following browsers to use this functionality:" %>
  <% end %>
  <div class="table">
    <%= render "_contracts_header.html", assigns %>
    <table width="1200" border="0" cellspacing="0" cellpadding="0" class="tablestyle1" >
			<tr>
				<td width="12%"><%= gettext "Case ID" %></td>
				<td width="28%"><%= gettext "Description" %></td>
        <td width="16%"><%= gettext "Sender" %></td>
				<td width="16%"><%= gettext "Recipient" %></td>
				<td width="10%"><%= gettext "Date" %></td>
				<td width="18%"><%= gettext "Status" %></td>
			</tr>
      <%= for contract <- @contracts do %>
        <tr>
          <td><%= detail_link(contract, :name_short, @conn, @locale) %></td>
          <td class="text-left"><%= detail_link(contract, :name, @conn, @locale) %></td>
          <td><%= sender_name(contract) %></td>
          <td><%= recipient_name(contract) %></td>
          <td><%= api_timestamp_to_datetimestring(contract.tx_time) %></td>
          <td><%= status_tag(contract) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="page"></div>
</div>

<div id="passphrase-input-modal" class="squared-modal modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <p><%= gettext "Please enter your passphrase to decrypt messages:" %></p>
        <div class="form-group">
        <input type="text" class="form-control" id="passphrase" placeholder="Passphrase..."
               data-invalid-passphrase-error-message="<%= gettext "Invalid passphrase, please try again." %>"
               data-passphrase-mismatch-error-message="<%= gettext "Incorrect passphrase, please try again." %>">
        <span id="passphrase-error" class="help-block hidden danger"></span>
      </div>
      <button id="submit-passphrase-btn" class="btn btn-default">Decrypt Attachment</button>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

web/templates/app/contract/show.html.eex
<div class="w1200 cont">
  <%= if Ipseeds.BrowserHelpers.partially_supported_browser?(@conn) do %>
    <%= render Ipseeds.SharedView, "_partially_supported_browser.html", additional_message: gettext "You will be unable to issue or decrypt contracts in your current browser. Please download one of the following browsers to use this functionality:" %>
  <% end %>
  <div class="table">
    <%= render "_contracts_header.html",
               Map.put(assigns, :detail_tab,
                       %{link: app_contract_path(@conn, :show, @locale, @conn.assigns.contract.api_transaction_id),
                        text: gettext("Data Contract Detail") }) %>
    <div class="details">
      <div class="tag2">
        <a class="on" href="#"><span><%= gettext "Data Contract" %></span></a>
      </div>
      <div class="addip">
        <div class="addiplist"><span><%= gettext "Issuer" %></span>
          <a href="<%= app_user_path(@conn, :show, @locale, @contract.issuer.username) %>">
            <%= @issuer_name %>
            (<%= @contract.issuer.username %>)
          </a>
        </div>
        <div class="addiplist"><span><%= gettext "Recipient" %></span>
          <a href="<%= app_user_path(@conn, :show, @locale, @contract.recipient.username) %>">
            <%= @recipient_name %>
            (<%= @contract.recipient.username %>)
          </a>
        </div>
        <div class="addiplist2 Phase"><span><%= gettext "Issue Date" %></span>
          <%= format_datetime @contract.updated_at %>
        </div>
      </div>
      <div class="listtitle2"><%= gettext "Data Contract Details" %></div>
      <div class="addip br1">
        <div class="addiplist3"><span><%= gettext "IP Notary Case ID" %></span>
          <%= @asset.name_short %></div>
        <div class="addiplist3"><span><%= gettext "IP Notary Title" %></span>
          <%= @asset.name %>
        </div>
        <div class="addiplist3"><span><%= gettext "IP Notary Asset ID" %></span>
          <%= @contract.api_sent_asset_id %>
        </div>
        <div class="addiplist3"><span><%= gettext "Transaction Entry Hash" %></span>
          <%= @contract.api_transaction_id %>
        </div>
        <div class="addiplist3"><span><%= gettext "Original Digital Signature (SHA256)" %></span>
          <%= @asset.hash_attachment %>
        </div>
        <%= if @contract.recipient.id != @current_user.id do %>
          <div class="addiplist3"><span><%= gettext "Attached File (encrypted)" %></span>
            <%= @contract.main_attachment.original_filename %>
          </div>
        <%= else %>
          <div style="border: 1px solid #eee; margin-left: 25px; padding: 15px;">
            <div class="alert alert-danger text-center" id="file-verification-failure" style="display: none;">
              <i class="fa fa-close"></i>
              <%= gettext "Digital Signatures Do Not Match! The attached file is not the same as the file used to digitally sign the IP Notary." %>
            </div>
            <div class="alert alert-success text-center" id="file-verification-success" style="display: none;">
              <i class="fa fa-check"></i>
              <%= gettext "Digital Signatures Match! The attached file is the same as the file used to digitally sign the IP Notary." %>
            </div>
            <h4>Download Attached File</h4>
            <p><%= gettext "Please click the button below to verify the attached file. You will be given the option to download the file after verification." %></p>
            <div class="addiplist3"><span><%= gettext "Attached File" %></span>
              <i class="fa fa-file-o"></i>
              <%= @contract.main_attachment.original_filename %>
            </div>
            <p style="display: none" class="text-center" id="file-is-verifying">
              <img class="inline-loading" src="<%= static_path @conn, "/images/loading.gif" %>"
                   alt="<%= gettext "Decrypting and Verifying File..." %>">
              <%= gettext "Decrypting and Verifying File..." %>
            </p>
            <div class="text-center">
              <a class="but03" href="#" id="verify-attached-file-btn" style="display: inline-block;">
                <i class="fa fa-shield"></i>
                <%= gettext "Verify Attached File" %>
              </a>
            </div>
            <div class="addiplist3" id="shared-file-hash-container" style="display: none;">
              <span><%= gettext "Attached File Digital Signature (SHA256)" %></span>
              <span id="shared-file-hash"></span>
            </div>
            <div class="text-center">
              <a class="but03" href="#" id="download-file-btn" style="display: none;">
                <i class="fa fa-download"></i>
                <%= gettext "Download File" %>
              </a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="passphrase-input-modal" class="squared-modal modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <p><%= gettext "Please enter your passphrase:" %></p>
      <div class="form-group">
        <input type="text" class="form-control" id="passphrase"
               placeholder="<%= gettext "Passphrase..." %>"
               data-invalid-passphrase-error-message="<%= gettext "Invalid passphrase, please try again." %>"
               data-passphrase-mismatch-error-message="<%= gettext "Incorrect passphrase, please try again." %>">
        <span id="passphrase-error" class="help-block hidden danger"></span>
      </div>
      <button id="submit-passphrase-btn" class="btn btn-default">
        <%= gettext "Decrypt and Verify File" %>
      </button>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->