web/router.ex
defmodule Ipseeds.Router do
  use Ipseeds.Web, :router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
    plug Ipseeds.LocalePlug, "en"
  end

  pipeline :csrf_protection do
    plug :protect_from_forgery
  end

  pipeline :public_layout do
    plug Ipseeds.CountingPlug
    plug :put_layout, {Ipseeds.LayoutView, :public}
  end

  pipeline :secure_app do
    plug Ipseeds.App.AuthPlug
    plug Ipseeds.App.KeypairCheckPlug
  end

  pipeline :app_layout do
    plug Ipseeds.CountingPlug
    plug Ipseeds.App.UnreadMessagesPlug
    plug Ipseeds.App.PendingContractsPlug
    plug :put_layout, {Ipseeds.LayoutView, :app}
  end

  pipeline :secure_admin do
    plug Ipseeds.Admin.AuthPlug, repo: Ipseeds.Repo
  end

  pipeline :admin_layout do
    plug :put_layout, {Ipseeds.LayoutView, :admin}
  end

  scope "/", Ipseeds do
    # Will redirect to /:locale/
    pipe_through [:browser, :csrf_protection]

    get "/", PageController, :dummy

    # add dummy route to allow links to this page with no locale to redirect to locale
    get "/users/reset_password", PageController, :dummy
  end

  scope "/:locale", Ipseeds do
    # Public routes (static pages, contact page)
    pipe_through [:browser, :csrf_protection, :public_layout]

    get "/", PageController, :index
    get "/privacy_policy", PageController, :privacy_policy
    get "/terms", PageController, :terms
    get "/features", PageController, :features
    get "/faq", PageController, :faq
    get "/about", PageController, :about
    get "/how_it_works", PageController, :how_it_works
    get "/pricing", PageController, :pricing
    get "/medium_rss_feed", PageController, :medium_rss_feed

    # Subscribe
    post "/subscribe", SubscribeController, :subscribe

    # Contact Page routes 
    get "/contact_us", ContactUsController, :new
    post "/contact_us", ContactUsController, :create

    # User Registration routes
    resources "/user_registrations", UserRegistrationController, only: [:new, :create]
    get "/user_registrations/thank_you", UserRegistrationController, :thank_you

    # Public User routes
    get "/users/forgot_password", UserController, :forgot_password
    post "/users/request_reset_password", UserController, :request_reset_password
    get "/users/reset_password", UserController, :reset_password
    post "/users/submit_new_password", UserController, :submit_new_password

    # Session routes
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    # Explorer routes
    resources "/explorer", App.ExplorerController, only: [:index, :show]
  end

  scope "/:locale", Ipseeds do
    pipe_through [:browser]
    post "/_reset_password_hook", UserController, :api_password_reset_hook

    # For monitoring
    get "/health_check", PageController, :health_check
  end

  scope "/:locale/secure", Ipseeds, as: :app do
    # App routes (main ipseeds functionality)
    pipe_through [:browser, :csrf_protection, :secure_app, :app_layout]

    get "/", App.IpDiscoveryController, :index
    get "/features", PageController, :features
    get "/privacy_policy", PageController, :privacy_policy
    get "/terms", PageController, :terms
    get "/faq", PageController, :faq
    get "/about", PageController, :about
    get "/how_it_works", PageController, :how_it_works

    get "/contact_us", ContactUsController, :new
    post "/contact_us", ContactUsController, :create

    # User settings routes
    get "/users/passphrase", App.UserController, :passphrase
    post "/users/passphrase", App.UserController, :create_passphrase
    post "/users/reset_password", App.UserController, :reset_password
    resources "/users", App.UserController, only: [:show, :edit, :update]
    post "/users/:id/update_profile_photo", App.UserController, :update_profile_photo

    # Ip Notary routes
    resources "/ip_notaries", App.IpNotaryController, only: [:new, :create, :index, :show]
    resources "/ip_summaries", App.IpSummaryController, 
      only: [:new, :create, :index, :show, :edit, :update]
    post "/ip_summaries/ip_notaries_list", App.IpSummaryController, :ip_notaries_list
    patch "/ip_summaries/:asset_id/hide", App.IpSummaryController, :hide
    patch "/ip_summaries/:asset_id/unhide", App.IpSummaryController, :unhide

    # Messages and contact list
    resources "/messages", App.MessageController, except: [:show]
    get "/messages/:username/:subject", App.MessageController, :show
    patch "/messages/mark_as_read/:user_id/:subject", App.MessageController, :mark_as_read
    resources "/user_contacts", App.UserContactController, only: [:index, :create, :delete]

    # Contract/Licensing
    resources "/contracts", App.ContractController, only: [:new, :create, :index, :show]

    get "/sessions/update", SessionController, :update
    
    # Explorer routes
    resources "/explorer", App.ExplorerController, only: [:index, :show]

    # Agreeable Contract routes
    resources "/agreeable_contract", App.AgreeableContractController, except: [:index, :delete]
    patch "/agreeable_contract/:id/cancel", App.AgreeableContractController, :cancel
    patch "/agreeable_contract/:id/decline", App.AgreeableContractController, :decline
  end

  scope "/:locale/admin", Ipseeds, as: :public_admin do
    # Public admin routes (no auth needed to view)
    pipe_through [:browser, :csrf_protection, :admin_layout]

    resources "/sessions", Admin.SessionController, only: [:new, :create, :delete]
    resources "/password_reset", Admin.PasswordResetController,
      only: [:new, :create, :edit, :update]
  end

  scope "/:locale/admin", Ipseeds, as: :admin do
    # Admin routes (TRPMA admin functionality)
    pipe_through [:browser, :csrf_protection, :secure_admin, :admin_layout]

    get "/", Admin.PageController, :dashboard

    resources "/admin_users", Admin.AdminUserController, except: [:show]
    resources "/user_registrations", Admin.UserRegistrationController,
      only: [:index, :show, :edit, :update]
    post "/user_registrations/:id/approve", Admin.UserRegistrationController, :approve
    post "/user_registrations/:id/disapprove", Admin.UserRegistrationController, :disapprove
  end
end

web/views/layout_view.ex
defmodule Ipseeds.LayoutView do
  use Ipseeds.Web, :view

  @doc """
  Renders current locale.
  """
  def locale do
    Gettext.get_locale(Ipseeds.Gettext)
  end

  @doc """
  Provides tuples for all alternative languages supported.
  """
  def fb_locales do
    Ipseeds.Gettext.supported_locales
    |> Enum.map(fn l ->
      # Cannot call `locale/0` inside guard clause
      current = locale()
      case l do
        l when l == current -> {"og:locale", l}
        l -> {"og:locale:alternate", l}
      end
    end)
  end

  @doc """
  Provides tuples for all alternative languages supported.
  """
  def language_annotations(conn) do
    Ipseeds.Gettext.supported_locales
    |> Enum.reject(fn l -> l == locale() end)
    |> Enum.concat(["x-default"])
    |> Enum.map(fn l ->
      case l do
        "x-default" -> {"x-default", localized_url(conn, "")}
        l -> {l, localized_url(conn, "/#{l}")}
      end
    end)
  end

  @doc """
  Provides class names from controller name and action name
  """
  def body_classes(conn) do
    case conn.path_info do
      [] -> ""
      [_head | tail] ->
        tail |> Enum.join(" ")
    end
  end

  def render("exagon.html", %{conn: conn}) do
    exagon_encoded = Ipseeds.ExagonHelpers.get_exagon(conn)
      |> Poison.encode!()

    ~E"""
    <script type="text/javascript">
      window.exagon = <%= {:safe, exagon_encoded} %>;
    </script>
    """
  end

  def current_date do
    Timex.now("Asia/Taipei") |> Timex.format!("{D} {Mshort}, {YYYY}")
  end

  defp localized_url(conn, alt) do
    # Replace current locale with alternative
    path = ~r/\/#{locale()}(\/(?:[^?]+)?|$)/
    |> Regex.replace(conn.request_path, "#{alt}\\1")

    Phoenix.Router.Helpers.url(Ipseeds.Router, conn) <> path
  end
end

web/templates/layout/_alerts.html.eex
<%= if alert_message = get_flash(@conn, :alert_message) do %>
  <% alert_type = get_flash(@conn, :alert_type) || "info" %>
  <div class="alert alert-<%= alert_type %>"><%= alert_message %></div>
<% end %>

web/templates/layout/_social_links.html.eex
<%= for social_site <- [
    %{name: "Facebook", url: "https://www.facebook.com/IPSeeds-899220550204929/", icon: "fb"},
    %{name: "Twitter", url: "https://twitter.com/BioIPseeds", icon: "tw"},
    %{name: "YouTube", url: "https://www.youtube.com/channel/UCLEZe3outPCnf2gwXvHienw", icon: "yt"}
] do %>
  <span>
    <a title="BioIPSeeds <%= social_site.name %>" href="<%= social_site.url %>" target="_blank">
      <img src="<%= static_path(@conn, "/images/#{social_site.icon}.png") %>"/>
    </a>
  </span>
<% end %>

web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Generate og:locale tags -->
  <%= for {property, content} <-fb_locales() do %>
    <%= Phoenix.HTML.Tag.tag(:meta, property: property, content: content) %>
  <% end %>

  <!-- Generate link alternate tags -->
  <%= for {lang, path} <-language_annotations(@conn) do %>
    <%= Phoenix.HTML.Tag.tag(:link, rel: "alternate", hreflang: lang, href: path) %>
  <% end %>

  <title>BioIPSeeds - Admin</title>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin.css") %>">
</head>
<body class="<%= body_classes(@conn) %>">

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_page_path(@conn, :dashboard, @locale) %>">
        <img src="<%= static_path(@conn, "/images/ipseeds.png") %>"/>
        <span>Admin</span>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= if @conn.assigns[:current_admin_user] do %>
          <li><%= link gettext("Dashboard"),
                       to: admin_page_path(@conn, :dashboard, @locale) %></li>
          <li><%= link gettext("User Registrations"),
                       to: admin_user_registration_path(@conn, :index, @locale) %></li>
          <%= if Ipseeds.AdminUser.is_superadmin? @current_admin_user do %>
            <li><%= link gettext("Admin Users"),
                       to: admin_admin_user_path(@conn, :index, @locale) %></li>
          <% end %>
          <li><%= link gettext("Logout"),
                     to: public_admin_session_path(@conn, :delete, @locale, @current_admin_user),
                     method: :delete %></li>
        <%= else %>
          <li><%= link gettext("Login"),
                       to: public_admin_session_path(@conn, :new, @locale) %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container" role="main">
  <%= render Ipseeds.LayoutView, "_alerts.html", conn: @conn %>
  <%= render @view_module, @view_template, assigns %>
</div> <!-- /container -->

<%= render Ipseeds.LayoutView, "admin_footer.html", assigns  %>

<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
<script src="<%= static_path(@conn, "/js/admin.js") %>"></script>
<script>require('web/static/js/admin').init();</script>
</body>
</html>

web/templates/layout/admin_footer.html.eex
<footer class="footer">
  <div class="container">
    <p>© <%= DateTime.utc_now.year %> Digital Treasury Corporation</p>
  </div>
</footer>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta property="og:title" content="BioIPSeeds">
  <meta property="og:type" content="web">
  <meta property="og:image" content="<%= static_path(@conn, "/images/1000x600.jpg") %>">
  <!-- Generate og:locale tags -->
  <%= for {property, content} <-fb_locales() do %>
    <%= Phoenix.HTML.Tag.tag(:meta, property: property, content: content) %>
  <% end %>

  <!-- Generate link alternate tags -->
  <%= for {lang, path} <-language_annotations(@conn) do %>
    <%= Phoenix.HTML.Tag.tag(:link, rel: "alternate", hreflang: lang, href: path) %>
  <% end %>

  <title>BioIPSeeds - Open Innovation Powered by Blockchain</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>
<body class="<%= body_classes(@conn) %>">
<div class="page-wrap">
  <div id="top" class="top">
    <div class="logo">
      <%= link to: app_ip_discovery_path(@conn, :index, @locale) do %>
        <img src="<%= static_path(@conn, "/images/ipseeds.png") %>"/>
      <% end %>
    </div>
    <%= render "app_user_menu.html", assigns %>
    <div class="number"><span><%= current_date() %></span><%= @asset_count %><span>
      Blockchain Records</span></div>
    <ul class="w1200 nav-top">
      <li class="<%= active_class_controller @conn, Ipseeds.App.IpDiscoveryController %>">
        <%= link gettext("Home"), to: app_ip_discovery_path(@conn, :index, @locale) %>
      </li>
      <li class="<%= active_class_controller @conn, [Ipseeds.App.IpNotaryController,
                                                     Ipseeds.App.IpSummaryController] %>">
        <%= link gettext("IP Notary"), to: app_ip_notary_path(@conn, :index, @locale) %>
      </li>
      <li class="<%= active_class_controller @conn, Ipseeds.App.ContractController %>">
        <%= link to: app_contract_path(@conn, :index, @locale) do %>
          <%= gettext("Contract Issuing") %>
          <%= if @pending_contract_count > 0 do %>
            (<%= @pending_contract_count %>)
          <% end %>
        <% end %>
      </li>
      <li class="<%= active_class_controller @conn, Ipseeds.App.MessageController %>">
        <%= link to: app_message_path(@conn, :index, @locale) do %>
          <%= gettext("Messages") %>
          <%= if @unread_message_count > 0 do %>
            (<%= @unread_message_count %>)
          <% end %>
        <% end %>
      </li>
      <li class="<%= active_class_controller @conn, Ipseeds.App.UserContactController %>">
        <%= link gettext("Contact List"), to: app_user_contact_path(@conn, :index, @locale) %>
      </li>
      <li class="<%= active_class_controller @conn, Ipseeds.App.ExplorerController %>">
        <%= link gettext("Explorer"), to: app_explorer_path(@conn, :index, @locale) %>
      </li>
    </ul>
  </div>
  <%= render Ipseeds.LayoutView, "_alerts.html", conn: @conn %>
  <!--main start-->
  <%= render @view_module, @view_template, assigns %>
  <!--main end-->
  <%= render "app_timeout_modal.html", assigns %>
</div>
<!--end .page-wrap-->
<!--footer-->
<div id="footer" class="graybg">
  <div>
      <span><img src="<%= static_path(@conn, "/images/ipseeds.png") %>"/></span>
      <span><%= link gettext("About"), to: app_page_path(@conn, :about, @locale) %></span>
      <span><%= link gettext("Features"), to: app_page_path(@conn, :features, @locale) %></span>
      <span><%= link gettext("How it works"), to: app_page_path(@conn, :how_it_works, @locale) %></span>
      <span><%= link gettext("FAQ"), to: app_page_path(@conn, :faq, @locale) %></span>
      <span><%= link gettext("Contact"), to: app_contact_us_path(@conn, :new, @locale) %></span>
      <span><%= link gettext("Privacy Policy"), to: app_page_path(@conn, :privacy_policy , @locale) %></span>
      <span><%= link gettext("Terms of Use"), to: app_page_path(@conn, :terms, @locale) %></span>
      <div>© 2017 Digital Treasury Corporation</div>
    </div>
</div>

<%= render_existing Ipseeds.LayoutView, "exagon.html", conn: @conn, locale: @locale %>
<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script>require('web/static/js/app').init();</script>
<%= if Mix.env == :prod do %>
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
 ga('create', 'UA-127760156-1', 'auto');
 ga('send', 'pageview');
 <%= raw Ipseeds.GaEventTrackingHelpers.sign_in_tracking(@conn, @current_user) %>
 ga('set', 'userId', '<%= @current_user.id %>');
</script>
<% end %>
</body>
</html>

web/templates/layout/app_timeout_modal.html.eex
<div id="sessionExtendModal" class="squared-modal modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <p><%= gettext "Your session will expire in 5 minutes. Please click \"Stay\" to continue using the site." %></p>
      <div align="center">
        <button data-dismiss="modal" id="extend_session" class="but03">
          <%= gettext "Stay" %>
        </button>
        <%= link gettext("Sign out"), to: session_path(@conn, :delete, @locale, @current_user),
                 method: :delete, class: "but03" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

web/templates/layout/app_user_menu.html.eex
<div id="user-menu" class="setting">
  <%= link to: app_user_path(@conn, :show, @locale, @current_user.username),
    id: "btn-profile", title: gettext "My profile" do %>
    <%= @current_user.username %>
    <span class="fa fa-id-card-o"></span>
  <% end %>
  <a id="btn-sign-out" data-toggle="modal" data-target="#logoutModal" 
    class="logout-btn btn btn-link" title="<%= gettext "Sign Out" %>">
    <span class="fa fa-sign-out"></span>
  </a>
</div>

<div id="logoutModal" class="logout squared-modal modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <p class="text-center"><%= gettext "Do you really want to sign out?" %></p>
      <div align="center">
        <button data-dismiss="modal" class="but03 cancel-btn"><%= gettext "Stay" %></button>
        <%= link gettext("Sign out"), to: session_path(@conn, :delete, @locale, @current_user),
                 method: :delete, class: "but03" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

web/templates/layout/email.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
    <div class="page-wrap">
      <!--main start-->
      <%= render @view_module, @view_template, assigns %>
      <!--main end-->
    </div>
    <!--end .page-wrap-->
  </body>
</html>

web/templates/layout/public.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="og:title" content="BioIPSeeds">
    <meta property="og:type" content="web">
    <meta property="og:image" content="<%= static_path(@conn, "/images/1000x600.jpg") %>">

    <!-- Generate og:locale tags -->
    <%= for {property, content} <-fb_locales() do %>
      <%= Phoenix.HTML.Tag.tag(:meta, property: property, content: content) %>
    <% end %>

    <!-- Generate link alternate tags -->
    <%= for {lang, path} <-language_annotations(@conn) do %>
      <%= Phoenix.HTML.Tag.tag(:link, rel: "alternate", hreflang: lang, href: path) %>
    <% end %>

    <title>BioIPSeeds - Open Innovation Powered by Blockchain</title>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/reset.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/public.css") %>">
  </head>

  <body class="<%= body_classes(@conn) %>">
    <div class="page-wrap">
      <div id="top">
        <div class="logo">
          <a href="<%= page_path(@conn, :index, @locale) %>">
            <img src="<%= static_path(@conn, "/images/ipseeds.png") %>"/>
          </a>
        </div>
        <div class="menu">
          <span class="<%= active_class_path @conn, page_path(@conn, :about, @locale), "on" %>">
            <%= gettext("About") |> String.upcase |> link(to: page_path(@conn, :about, @locale)) %>
          </span>
          <span class="<%= active_class_path @conn, page_path(@conn, :features, @locale), "on" %>">
            <%= gettext("Features") |> String.upcase |> link(to: page_path(@conn, :features, @locale)) %>
          </span>
          <span>
            <%= gettext("How It Works") |> String.upcase |> link(to: page_path(@conn, :how_it_works, @locale)) %>
          </span>
          <span class="<%= active_class_path @conn, explorer_path(@conn, :index, @locale), "on" %>">
            <%= gettext("Explorer") |> String.upcase |> link(to: explorer_path(@conn, :index, @locale)) %>
          </span>
        </div>
        <div class="number"><span><%= current_date() %></span><%= @asset_count %><span>
          <%= gettext "Blockchain Records" %></span></div>
      </div>
      <!--main start-->
      <%= render @view_module, @view_template, assigns %>
      <!--main end-->
    </div>
    <!--end .page-wrap-->

    <!--footer-->
    <div id="footer" class="graybg">
      <div>
          <span><img src="<%= static_path(@conn, "/images/ipseeds.png") %>"/></span>
          <span><%= link gettext("About"), to: page_path(@conn, :about, @locale) %></span>
          <span><%= link gettext("FAQ"), to: page_path(@conn, :faq, @locale) %></span>
          <span><%= link gettext("Contact"), to: contact_us_path(@conn, :new, @locale) %></span>
          <span><%= link gettext("Pricing"), to: page_path(@conn, :pricing, @locale) %></span>
          <span><%= link gettext("Privacy Policy"), to: page_path(@conn, :privacy_policy , @locale) %></span>
          <span><%= link gettext("Terms of Use"), to: page_path(@conn, :terms, @locale) %></span>
          <div>© 2017 Digital Treasury Corporation</div>
        </div>
    </div>
    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/public.js") %>"></script>
    <script>require('web/static/js/public').init();</script>
    <%= if Mix.env == :prod do %>
    <script>
     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
     m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
     ga('create', 'UA-91840689-1', 'auto');
     ga('send', 'pageview');
    </script>
    <% end %>
  </body>
</html>